# serverless.yml

app: dimple-smile-cos # (否) 该应用名称
stage: dev # (否) 用于区分环境信息，默认值为 dev

component: cos # (是) 组件名称，此处为 cos
name: dimple-smile-cos # (是) 实例名称

inputs:
  bucket: dimple-smile
  protocol: https
  region: ap-guangzhou
  replace: false # ⚠️⚠️⚠️部署时会先清理桶内所有文件，谨慎使用！！！
  website: false
  cors:
    - maxAgeSeconds: 0
      allowedMethods:
        - GET
      allowedOrigins:
        - '*'
      allowedHeaders:
        - '*'
      exposeHeaders:
        - ''
